// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQO7vWBbs60Tuc5n-EVTTyAgAQyh9yo9g',
    appId: '1:449082548696:web:872ae39faed324268c12ad',
    messagingSenderId: '449082548696',
    projectId: 'flutter-app-distribution-90135',
    authDomain: 'flutter-app-distribution-90135.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-90135.firebasestorage.app',
    measurementId: 'G-FR49MTQ4VJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8jLcC9JQN65BQr_xr7PI3GZbTnelMEjQ',
    appId: '1:449082548696:android:44ac88387513c52d8c12ad',
    messagingSenderId: '449082548696',
    projectId: 'flutter-app-distribution-90135',
    storageBucket: 'flutter-app-distribution-90135.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Nrvspg8GZvAkMpy0FKfiiEkdrZX-O4k',
    appId: '1:449082548696:ios:7472dc94fb8ffb8d8c12ad',
    messagingSenderId: '449082548696',
    projectId: 'flutter-app-distribution-90135',
    storageBucket: 'flutter-app-distribution-90135.firebasestorage.app',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Nrvspg8GZvAkMpy0FKfiiEkdrZX-O4k',
    appId: '1:449082548696:ios:7472dc94fb8ffb8d8c12ad',
    messagingSenderId: '449082548696',
    projectId: 'flutter-app-distribution-90135',
    storageBucket: 'flutter-app-distribution-90135.firebasestorage.app',
    iosBundleId: 'com.example.myApp1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQO7vWBbs60Tuc5n-EVTTyAgAQyh9yo9g',
    appId: '1:449082548696:web:e6b1aff83128a0d88c12ad',
    messagingSenderId: '449082548696',
    projectId: 'flutter-app-distribution-90135',
    authDomain: 'flutter-app-distribution-90135.firebaseapp.com',
    storageBucket: 'flutter-app-distribution-90135.firebasestorage.app',
    measurementId: 'G-T2YMKJBX52',
  );
}
